### ISSUE TITLE
Agendas & Minutes locked by meeting participants

### ISSUE THREAD

**Issue by SMPTE-standards** [SMPTE/smpte-skn-platform#10]
When a meeting participant opens an agenda in teams, it becomes locked in Sharepoint. Closing the Teams app in this state keeps the document locked until some unknown timeout occcurs (possibly the end of the universe).

The meeting chair cannot update the locked agenda status from draft to be approved until the non-reponsive meeting member finally re-opens the app and then closes the document.

I could not find a way to have a folder where the default access is "comment" or to enforce checkout/checkin to prevent this. Expert opinions welcome on how a chair can manage the metadata betterer.

**Comment by tbause** [comment]
Could not replica. Issue may be resolved by MS. Please reopen if this is still an issue.
