### ISSUE TITLE
Project Activities

### ISSUE THREAD

**Issue by pngardiner** [SMPTE/smpte-skn-platform#13]
Not of immediate urgency, but I believe we should develop a method of adding Activities to Projects similar to the way this was done on OLC. 

While automatically placing Projects in the correct 'bucket' according to its % progress is useful, being able to log Activities and their dates gives a much better view of a Project's progress and can be used as a check that no key stage in the process has been missed. 

At its simplest, adding text to the Notes could achieve this. But there might be a better way.

**Comment by tbause** [comment]
This issue is obsolete
