### ISSUE TITLE
"All Teams" calendar timezone different from other Team calendars

### ISSUE THREAD

**Issue by PaulTreleaven** [SMPTE/smpte-skn-platform#16]
This issue is not something that can sensibly be changed, but I have requested that a warning goes into the user guide. 
The " My Teams" calendar displayed on the left-hand pane of Teams uses the member's own local timezone - at least it does when the account is sync'd with the member's desktop Outlook. 
This is also true of the individual Team calendar at the top of each Team. *This calendar is used by organizers to schedule meetings*

However, the "All Teams" calendar is set to Eastern USA timezone (because it is shared by all users). *This calendar is used by organizers to check for availability before scheduling meetings*

So organizers need to be aware of this (potential) difference to avoid mistakes when scheduling meetings. The warning needs to be added to the SKN User Guide.

**Comment by tbause** [comment]
Documentation updated.
