### ISSUE TITLE
Bad link to SKN User Guidelines

### ISSUE THREAD

**Issue by bgschunck** [SMPTE/smpte-skn-platform#17]
When I try to use this [link](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fteams.microsoft.com%2Fl%2Ffile%2F105388C2-C029-434B-A6B1-55B4A4C2E1DF%3FtenantId%3Dc6051a58-269b-4f08-835f-eedebf4596b3%26fileType%3Ddocx%26objectUrl%3Dhttps%253A%252F%252Fsmpte.sharepoint.com%252Fsites%252FSCStandardsCommunity%252FShared%2520Documents%252FStandards%2520Information%252FMigration%2520Documents%252FSKN-Guidelines-user-rev20201220.docx%26baseUrl%3Dhttps%253A%252F%252Fsmpte.sharepoint.com%252Fsites%252FSCStandardsCommunity%26serviceName%3Dteams%26threadId%3D19%3A9de925da39d94f509d0374cf9ba5b738%40thread.tacv2%26groupId%3D8a648854-73b1-4fa3-8001-6b62a49efe53&data=04%7C01%7Cbschunck%40m.smpte.org%7Cf39b3316e1824cce2cad08d8b8d89103%7Cc6051a58269b4f08835feedebf4596b3%7C0%7C0%7C637462587678122292%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=IhDwiLBxHLQ3wguDdtpjch1eMUnft46bXzwwB9F2m10%3D&reserved=0) send in an email, get a weird error in Teams on the web. See attached screenshot.

My email client is Outlook Desktop app and the browser is Microsoft Edge.

![Screen Shot 2021-01-27 at 10 58 30 AM](https://user-images.githubusercontent.com/7690866/106190269-46f1bd80-615e-11eb-8e66-b5534fd47fa6.png)

**Comment by tbause** [comment]
User guide moved to the website.
