### ISSUE TITLE
FCD Ballot Link Not Working

### ISSUE THREAD

**Issue by bgschunck** [SMPTE/smpte-skn-platform#22]
The link to the document package in the email for a recent FCD ballot is not working. Marked the bad link with the title "NOT WORKING". When I try to use the link from the Teams desktop app (Windows 10), nothing happens.

The portion of the email:

Name of FCD Ballot: Approval of
31FS-CD-ST-2065-5-ACES MXF Revision-2021-02-03(FCD-ballot-package).zip 

The document package can be accessed at ...

[NOT WORKING](https://smpte.sharepoint.com/sites/TC-31FSFileFormatsandSystems/_layouts/15/DocIdRedir.aspx?ID=31FS-1334357839-63240)

The FCD Ballot will start: 2021-02-09 11:59 PM (ET)
The FCD Ballot will end: 2021-03-16 11:59 PM (ET)

NOTE: The form will not be accepting responses until after the start time and after the end time.

Link to FCD Ballot
https://teams.microsoft.com/l/channel/19%3afb90cd974c124ea08a6c40d83dcef4bd%40thread.tacv2/tab%3a%3abcf44442-804e-4720-91ed-341a7976822c?label=FCD+Ballot+31FS-CD-ST-2065-5-ACES+MXF+Revision-2021-02-03(FCD-ballot-package).zip&groupId=2a84eaec-4488-4f92-95c6-85c4fe10141e&tenantId=c6051a58-269b-4f08-835f-eedebf4596b3

Please vote

**Comment by tbause** [comment]
Have you looked at the bottom of the browser window? The link will not open a page but rather download a zip file (the document package). A download indicator will be shown on the bottom left of the browser window. The file is also located in the download folder of your computer. This is a link to the document package and not a link to the SharePoint site where the document package is located.

Best Regards

Thomas


Thomas Bause Mason
Director of Standards Development
SMPTE®
+1 914 205 2378
+1 347 839 7569
 www.smpte.org
​

**Comment by bgschunck** [comment]
Like I said, the link does not work. Had to reverse engineer how to get a
URL and download the package. Took too long, confusing.

Much better to have a short name that clearly describes where the ballot
package is, like "31FS Balot Documents", and that phrase could be the label
for a link taking us to the correct location. If the link works, great. If
not, we have a canonical name for the folder location. I fear it will take
a long time to track down these link problems. In the meantime, just
knowing where to look for the package is fine. Teams is so much faster than
OLC that a couple of mouse clicks is very fast.

I am super happy we switched.

--
Brian Schunck
Cell: (858) 526-0797

**Comment by tbause** [comment]
I will try and incorporate the file location into the notification as a folder path once I have some time. The next few ballots or votes will go out as is until I incorporated the changes.

**Comment by tbause** [comment]
This was done. The mechanism for ballots changed and I think this can be closed.
