### ISSUE TITLE
Ballot pages are blank in Teams app

### ISSUE THREAD

**Issue by palemieux** [SMPTE/smpte-skn-platform#24]
![https://teams.microsoft.com/l/channel/19%3A40c0b2b1785d41aca525d39c1381170b%40thread.tacv2/tab%3A%3A82f9b999-542c-4787-ba13-d13d8c533931?groupId=2a84eaec-4488-4f92-95c6-85c4fe10141e&tenantId=c6051a58-269b-4f08-835f-eedebf4596b3](https://user-images.githubusercontent.com/4871350/112227982-bd0a2200-8bed-11eb-8c30-adf0d8f77ed4.png)

https://teams.microsoft.com/l/channel/19%3A40c0b2b1785d41aca525d39c1381170b%40thread.tacv2/tab%3A%3A82f9b999-542c-4787-ba13-d13d8c533931?groupId=2a84eaec-4488-4f92-95c6-85c4fe10141e&tenantId=c6051a58-269b-4f08-835f-eedebf4596b3

**Comment by tbause** [comment]
This appears to happen when users access the ballot through the Teams desktop app. The issues should be resolved when using the browser based Teams web app.

**Comment by tbause** [comment]
Not relevant anymore
