### ISSUE TITLE
[SKN General] Folder for automated member list

### ISSUE THREAD

**Issue by tbause** [SMPTE/smpte-skn-platform#29]
Could we get the automated list pushed into a folder within “Administration” that doesn’t change names (such as “Automated_Member_List”)? You can still use the naming convention you have for the file. It’ll make a Power Query much easier if I can use a hot folder like this, rather than a folder with other files and/or wildcarding a filename.

**Comment by sgusciora-smpte** [comment]
Automated member lists are now located in the automated_member_list folder in the Administration folder for each TC.
