### ISSUE TITLE
[Roster Spreadsheet] bug in P-Member Remove calc

### ISSUE THREAD

**Issue by billredmann** [SMPTE/smpte-skn-platform#39]
The Roster Spreadsheet Guide documents the "P-Member remove" column (column H) consistently with the column's behavior, however the OM is interpreted incorrectly, resulting in under-reporting of P-Members that should be removed.

Accordingly, this bug affects both the Roster Spreadsheet and the Roster Spreadsheet Guide.

The OM states 3.2.3.3 "in order to retain their status, shall not miss more than two meetings in a row and shall not fail to vote on more than three written votes in a row" (this is correctly quoted in the Guide).
 
Mathematically, the OM is saying  RETAIN = NOT(FAIL_MEETINGS) AND NOT(FAIL_VOTE)
  where
    FAIL_MEETINGS is "miss more than two meetings in a row" and
    FAIL_VOTE is "fail to vote on more than three written votes in a row"

The columns "Meeting Eligibility" (col i) and "Voting Eligibility" (col N) compute FAIL_MEETINGS and FAIL_VOTE, respectively.

The column "P-Member Remove" is intended to express NOT(RETAIN).

In Boolean operations, NOT ( NOT(A) AND NOT(B) ) is the same as A OR B

As applied to this situation, "P-Member remove" should compute NOT(RETAIN) = FAIL_MEETINGS OR FAIL_VOTE

however, the equation in column H is  FAIL_MEETINGS AND FAIL_VOTE, which is incorrect, resulting in the improper retention of P-MEMBERS who should not be retaining P-MEMBER status.

**PROPOSED SOLUTION:
  change the AND() function in column H, to OR().**

i.e., change
  =IF(AND(I2="Warning",  N2="Warning"),"Remove","")
to
  =IF(OR(I2="Warning",  N2="Warning"),"Remove","")

[BTW, a side-effect of this bug is a lock-in effect for P-Members documented as having been ineligible to vote... so long as someone is ineligible to vote, in any of the past four ballots, the FAIL_VOTE equation will (correctly) not result in "Warning".  If the state for the most recent ballot is "ineligible", then it will be so for all future ballots, and the "FAIL_VOTE" status of "Warning" can never become true (without chair intervention), hence the lock-in effect.  This effect goes away immediately upon implementation of the above proposed solution.]

**Comment by billredmann** [comment]
Also, in the documentation, on page 4, in the section on "H. P-Member Remove", second bullet,
  Change the phrase
"This is a calculated field that check fields I and N. If both are warnings, and Member’s..."
  to
"This is a calculated field that check fields I and N. If either are warnings, and Member’s..."

**Comment by tbause** [comment]
Closed due to publication of roster app. Roster spreadsheet is deprecated.
