### ISSUE TITLE
[Upload App] - No notes or user text?

### ISSUE THREAD

**Issue by SteveLLamb** [SMPTE/smpte-skn-platform#40]
I'm looking at the upload tool and wanting to utilize this, but I'm not seeing any option either in the instructions or the panels that allow for user text on the notice to the channel. Am I missing this?

**Comment by sgusciora-smpte** [comment]
If you have the "Send notification to channel" checkbox checked and then have a file selected to upload, you should see the field on the very bottom to enter comments which will be added to the channel notification.

**Comment by tbause** [comment]
@SteveLLamb can we close this issue?

**Comment by SteveLLamb** [comment]
Yes, it was confusing because the box doesn't show up until a file is attached. That should be noted in the informational dialogue, so other people don't try it out and decide not to use because it appears not to have this function (as I did). Such as, "After file selection, field to enter comments to be added to the notification will appear" or something similar.
