### ISSUE TITLE
[Project App] Document Type needed for Metadata Register releases

### ISSUE THREAD

**Issue by billredmann** [SMPTE/smpte-skn-platform#43]
The Project App supports tracking of "Status" (e.g., WD, FCD, Published, etc.) but access to the pick-list for setting current status requires "Document Type" to be set.  The work of 30MR includes update of Metadata Registers, which per §5.2.5 of the OMs "shall be subject to the normal Engineering Document process" (in many/most casts), but Metadata Registers are not of type ST, RP, EG, etc.  Can we add a "Metadata Register" (or perhaps "MR") Document Type to allow easy access to the Status field pick-list functionality.

**Comment by tbause** [comment]
We set up an "Other" type for things that do not fall under the default, engineering doc types

**Comment by tbause** [comment]
We set up an "Other" type for things that do not fall under the default, engineering doc types

**Comment by palemieux** [comment]
There is in fact an engineering document associated with registers ([ST 2123](https://pub.smpte.org/doc/st2123/20220924-pub/)), so why create a new document type?

**Comment by raymondyyeungDBL** [comment]
The registers release has been following the doc development process as ST. Working well so far.
