### ISSUE TITLE
[Uploads App] Using app causes Power Automate trigger

### ISSUE THREAD

**Issue by SteveLLamb** [SMPTE/smpte-skn-platform#44]
When using the Uploads App, it will trigger Power Automate to send a chat message asking if you want to share the link, as if you upload the document normally via Teams or Sharepoint. See below. I used the Uploads App for this document. 

![Screen Shot 2023-05-11 at 2 02 00 PM](https://github.com/SMPTE/smpte-skn-platform/assets/38917682/52311624-1f68-4d5b-88ae-1177fc97f90f)

**Comment by SteveLLamb** [comment]
This is still an issue as well.

**Comment by tbause** [comment]
The Upload App will be deprecated and replaced by the new Documents App. It will be fixed in the Documents App

**Comment by SteveLLamb** [comment]
Noted.
