### ISSUE TITLE
[Uploads App] Closed groups

### ISSUE THREAD

**Issue by SteveLLamb** [SMPTE/smpte-skn-platform#45]
Upload app should be filtered from groups that have been marked as [CLOSED]. Those groups should not be uploaded to.

**Comment by SteveLLamb** [comment]
This is still an issue.

**Comment by tbause** [comment]
This app will be deprecated shortly and incorporated in the new Documents App. We will account for that there.

**Comment by SteveLLamb** [comment]
Noted.
