### ISSUE TITLE
[Roster App] Link to meeting attendance record

### ISSUE THREAD

**Issue by SteveLLamb** [SMPTE/smpte-skn-platform#48]
There is currently no way to link to a specific meeting attendance record. The only link available is to the the main roster app page. https://teams.microsoft.com/_#/apps/428c538c-d714-4f5b-bbd9-64508388db74/sections/7faee356-fb1a-4ebd-9cb7-c6917b3dee56. We need to be able to have links to meetings for plenary minutes and agenda records, as it currently takes several clicks to find a meeting (will be very problematic once we have a few meeting cycles logged).

**Comment by sgusciora-smpte** [comment]
This feature has been added and released. The link can be retrieved on the bottom right of the plenary attendance list and should take you directly to the attendance list screen in the app. See screenshot:
![image](https://github.com/SMPTE/smpte-skn-platform/assets/94081521/2b4064c4-4e20-44eb-90e9-d663d907ccbc)

We may change the text or the location of the link at a later time.
