### ISSUE TITLE
[Roster App] incorrect meeting tallying

### ISSUE THREAD

**Issue by SteveLLamb** [SMPTE/smpte-skn-platform#49]
The meeting attendance flags for `not met` are not triggering right. See both Ioan Allen and Phillip Newell in 27C. Both have attended this Dec's meeting, but it's showing the flag to warn for missing 2 meetings in a row, where it should be 3 in a row ("shall not miss more than two meetings in a row" as per the OM).

**Comment by sgusciora-smpte** [comment]
It looks like both of these users had the attendance flags update during the daily recalculation of the meeting attendance/vote participation flags done every night. If you are modifying attendance on the plenary attendance list screen, it will only recalculate during the scheduled recalculation to help the performance of the app. Each time the app calls a flow, it slows down briefly. To better support the speed of using the attendance modifiers during a meeting, we opted to not make any calls to recalculate from there. If you modify the attendance on the individual user's profile for a TC, it will recalculate immediately. We can explore having the values update in a more instantaneous way.

**Comment by tbause** [comment]
We will add a text to the SKN User Guide.
