### ISSUE TITLE
[Voting App] show most recent resolution proposal to editor typing a reponse

### ISSUE THREAD

**Issue by mrmxf** [SMPTE/smpte-skn-platform#50]
While typing responses to comment, you have to open the voting app in a new window or have a good memory if you want to correctly copy from a previous resolution /response.

Adding an extra box to show the most recent resolution makes the system more useable. Better still have a means to select any of the previous resolution  / responses.

**Comment by tbause** [comment]
This is an easy fix. we will add the function this week.

**Comment by tbause** [comment]
This fixed
