### ISSUE TITLE
[Documents App] Closed groups

### ISSUE THREAD

**Issue by SteveLLamb** [SMPTE/smpte-skn-platform#54]
Closed and Archived groups should be hidden by default or option to "show" hidden. Documents should not be uploaded to closed and archived groups anyhow, so I don't see a reason to even show them at all. 

![Screenshot 2024-08-14 at 10 00 51 AM](https://github.com/user-attachments/assets/bb342757-5b60-49f4-bb6e-0000091803d5)

**Comment by sgusciora-smpte** [comment]
Duplicate #60
