### ISSUE TITLE
Rosters app throwing server error and leaving fields unpopulated.  Sometimes.

### ISSUE THREAD

**Issue by billredmann** [SMPTE/smpte-skn-platform#56]
[Rosters]   Opened the Rosters app, selected 30MR, and received this message:

> An error occurred on the server. Server Response: DEV-TC-Member-Roles-Enumeration failed: The response is not in a JSON format.

  Coinciding with the error, the “Category” column is empty (that is, none of the selector boxes is populated with current values, nor do the selector boxes offer allowed values.

  Other columns, "Meeting Attendance" and "Vote Participation" appear populated appropriately and their values seem reasonable upon casual inspection. Similarly, the Eligibility column contains a few values (mostly empty) but these include “P-Member Eligible” and “Warning”, and so to casually inspection, this appears to be working, too.

  While still in Rosters, when navigating to individual 30MR members’ "View Member" pages, the app sometimes throws an error (I didn’t catch it before it disappeared, different than above, though it said something about “server”) which coincides with the "Vote Participation" field failing to populate.  Other times, for the same or different members, it populates just fine.

  Maybe there’s an issue with a query timeout being too short? (The pages, error or no, populate pretty fast, maybe under two seconds?)

  Everything seems to work eventually, but not initially (and I'm sure it's been weeks since I've run the Rosters app).

**Comment by sgusciora-smpte** [comment]
If you try the app now do you still have issues? I tested the app yesterday and again this morning and had no issues with loading data from the SharePoint tables. Thomas also tested it and he did not have any issues. I think it may have been an issue with SharePoint at the time. If it seems to be working we can close this issue.

**Comment by billredmann** [comment]
Scott,  I agree - it seems to have been a weird transient behavior.  It worked without issue for me this morning (less comprehensive, but still).  -Bill-----Bill Redmann(818) ***@***.*** Nov 5, 2024, at 12:13 PM, Scott Gusciora ***@***.***> wrote:﻿
If you try the app now do you still have issues? I tested the app yesterday and again this morning and had no issues with loading data from the SharePoint tables. Thomas also tested it and he did not have any issues. I think it may have been an issue with SharePoint at the time. If it seems to be working we can close this issue.
