### ISSUE TITLE
Possible meeting issue - Screen shares

### ISSUE THREAD

**Issue by SteveLLamb** [SMPTE/smpte-skn-platform#8]
Mac Chrome [Mac OS 10.15.7, Chrome Version 86.0.4240.193 (Official Build) (x86_64)]

- When presenters are changing screen share to another user, video freezes, requires meeting attendee to log out of meeting and log back in.

**Comment by tbause** [comment]
Is this still an issue?

**Comment by tbause** [comment]
This is nothing we can control. This is a software client issue which needs to be fixed by MS.
