### ISSUE TITLE
GitHub not Visible via Web version of Teams 

### ISSUE THREAD

**Issue by SteveLLamb** [SMPTE/smpte-skn-platform#9]
Standalone version works fine. This will be an issue if we are doing work through teams. User can go directly to GitHub, so links should be provided within the Team, so that people aren't searching around

<img width="1350" alt="Screen Shot 2020-11-18 at 10 31 00 AM" src="https://user-images.githubusercontent.com/38917682/99572222-30bec880-2989-11eb-8669-91aa2a0bf003.png">

**Comment by tbause** [comment]
Need to follow up.

**Comment by tbause** [comment]
Could not replicate. Please reopen if this is still an issue.
